version: '3.8'

services:
  app:
    image: php:8.2-fpm  # Gunakan image PHP yang sesuai
    container_name: wms_toho
    ports:
      - "9001:9001"  # Expose port 8000
    volumes:
      - ./src:/var/www/html  # Mount folder proyek lokal ke dalam container
    networks:
      - laravel_network

  web:
    image: nginx:alpine  # Gunakan image Nginx untuk server web
    container_name: laravel_web
    ports:
      - "8080:80"  # Expose port 8080 di localhost
    volumes:
      - ./src:/var/www/html  # Mount folder proyek lokal ke dalam container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Konfigurasi Nginx
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:5.7  # Gunakan image MySQL
    container_name: mysql_5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mws_toho
      MYSQL_USER: root
      MYSQL_PASSWORD: pmapass
    ports:
      - "3306:3306"  # Expose port MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persist database
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
    driver: local
